[package]
name = "mote-cube"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["cpu"]
cpu = ["cubecl/cpu"]
cuda = ["cubecl/cuda"]
hip = ["cubecl/hip"]
vulkan = ["cubecl/vulkan"]

[dependencies]
mote-kernel = { path = "../mote-kernel" }
mote-types = { path = "../mote-types" }
cubecl = { workspace = true, features = ["std", "stdlib"] }
