[package]
name = "mote-cube"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
cpu = ["cubecl/cpu"]
cuda = ["cubecl/cuda"]
hip = [
    "cubecl/hip",
    "dep:cubecl-runtime",
    "dep:cubecl-hip-sys",
]
vulkan = ["cubecl/vulkan"]

[dependencies]
mote-kernel = { path = "../mote-kernel" }
mote-types = { path = "../mote-types" }
mote-core = { path = "../mote-core" }
thiserror.workspace = true
cubecl = { workspace = true, features = ["std", "stdlib"] }
cubecl-runtime = { workspace = true, optional = true }
cubecl-hip-sys = { workspace = true, optional = true }
cubek-matmul.workspace = true
cubek-std.workspace = true
half.workspace = true

[[bench]]
name = "matmul_hip"
harness = false
required-features = ["hip"]
